services:
  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: nexusfin
      POSTGRES_PASSWORD: nexusadmin
      POSTGRES_DB: rootDatabase
    ports:
      - "5432:5432"
    command:
      postgres -c log_min_messages=warning
    
  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
    - "4000:4000"
    environment:
      NODE_ENV: production
      databaseUrl: postgres://nexusfin:nexusadmin@database:5432/rootDatabase
      JWT_KEY: 8tNv5J6A7g5UplF0omFn
      URL_Client: http://client:3000
      PORT: 4000
      SYNC: true

  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
      args:
        URL_Server: http://server:4000
    ports:
    - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
    
volumes:
  pgdata:
